name: hanabudget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_custom_clippers: ^2.1.0
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  fl_chart: ^0.69.0
  uuid: ^4.5.0
  mongo_dart: ^0.10.0
  shared_preferences: ^2.2.2
  debounce_throttle: ^2.0.0
  mailer: ^6.0.0
  crypto: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/tinylogo.png
    - .env  # Add this if you want to include .env file as an asset